# Generated by Django 2.0.7 on 2018-09-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('validated', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='bucket',
            name='order',
            field=models.ManyToManyField(related_name='orders', to='shop.Order'),
        ),
    ]
